#!/usr/bin/env sh

# Color Palette
# Tokyonight Night
BLACK=0xff24283b
WHITE=0xffa9b1d6
MAGENTA=0xffbb9af7
BLUE=0xff7aa2f7
CYAN=0xff7dcfff
GREEN=0xff9ece6a
YELLOW=0xffe0af68
ORANGE=0xffff9e64
RED=0xfff7768e
BROWN=0xff9c6f64
BAR_COLOR=0xff1a1b26
COMMENT=0xff565f89

TRANSPARENT=0x00000000
HOVER_COLOR=0xff3b4261

# General bar colors
ICON_COLOR=$WHITE  # Color of all icons
LABEL_COLOR=$WHITE # Color of all labels

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="JetBrainsMono NF"
APP_ICON_FONT="sketchybar-app-font:Regular"

PADDINGS=3

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11
POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$COMMENT

CORNER_RADIUS=15
BORDER_WIDTH=2

POMODORO_COLOR=$RED
POMODORO_COOLDOWN_COLOR=$GREEN
POMODORO_HIGHLIGHT_COLOR=0xff0a0b16

CRON_COLOR=0xffc6a679

SHADOW=on
