#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults

sketchybar --bar height=30 \
	color="$BAR_COLOR" \
	shadow="$SHADOW" \
	position=top \
	sticky=on \
	padding_right=10 \
	padding_left=10 \
	padding_top=10 \
	padding_bottom=10 \
	corner_radius=0 \
	y_offset=0 \
	margin=0 \
	blur_radius=0 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:13.0" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
	popup.background.border_width=1 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"

# Left

# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Left
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/keyboard.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/pomodoro.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/cpu.sh"
# source "$ITEM_DIR/wallet.sh"
source "$ITEM_DIR/caffeinate.sh"
source "$ITEM_DIR/pomodoro.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true

sketchybar --update

echo "sketchybar configuration loaded.."
