{ lib, config, namespace, pkgs, ... }:
let
  inherit (lib) mkIf mkMerge optionalString;
  inherit (lib.${namespace}) mkBoolOpt mkStableBinTCC;

  cfg = config.${namespace}.apps.yabai;
  userCfg = config.${namespace}.core.user;

  # Stable path on the filesystem that macOS TCC keys on. nix store paths
  # change every rebuild, which silently revokes Accessibility / Input
  # Monitoring permission for yabai. Copying the binary to a fixed path
  # keeps TCC stable across rebuilds.
  stableBin = "/usr/local/bin/yabai";

  # Reconstruct the yabairc path the same way nix-darwin's services.yabai module
  # does, so launchd gets the same -c argument it would have without the override.
  toYabaiConfig = opts:
    lib.concatStringsSep "\n" (lib.mapAttrsToList
      (p: v: "yabai -m config ${p} ${toString v}")
      opts);

  yabairc = pkgs.writeScript "yabairc" (
    (if config.services.yabai.config != { } then toYabaiConfig config.services.yabai.config else "")
    + optionalString (config.services.yabai.extraConfig != "") ("\n" + config.services.yabai.extraConfig + "\n")
  );
in
{
  options.${namespace}.apps.yabai = {
    enable = mkBoolOpt false "Enable yabai module";
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.yabai;
      description = "Package to use for yabai window manager.";
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      services.yabai = {
        enable = true;
        config = {
          mouse_follows_focus = "off";
          window_origin_display = "default";
          window_placement = "second_child";
          window_opacity = "off";
          window_shadow = "on";
          window_opacity_duration = 0.0;
          active_window_opacity = 1.0;
          normal_window_opacity = 0.9;
          window_border = "off";
          window_border_width = 6;
          active_window_border_color = "0xff775759";
          normal_window_border_color = "0xff555555";
          insert_feedback_color = "0xffd75f5f";
          split_ratio = 0.5;
          auto_balance = "off";
          mouse_modifier = "fn";
          mouse_action1 = "move";
          mouse_action2 = "resize";
          mouse_drop_action = "swap";
          external_bar = "all:35:0";
          top_padding = 12;
          bottom_padding = 12;
          left_padding = 12;
          right_padding = 12;
          window_gap = 20;
          layout = "bsp"; # default "float" (windows are not managed)
        };

        # WARN: Yabai scription addition requires Security Integration Protection to be partially disabled.
        # 1. In OSX Recovery mode terminal (long press power button during boot) run the following command:
        # > csrutil enable --without fs --without debug --without nvram
        # 2. In normal mode enable non-Apple signed binaries:
        # > sudo nvram boot-args=-arm64e_preview_abi
        # 3. Reboot again
        enableScriptingAddition = true;
        extraConfig = ''
          # Use the nix-store binary for --load-sa so it matches the sha256-pinned
          # sudoers entry generated by enableScriptingAddition. The stable /usr/local/bin
          # copy is for TCC (Accessibility) only.
          sudo "${cfg.package}/bin/yabai" -m signal --add event=dock_did_restart action="sudo '${cfg.package}/bin/yabai' --load-sa"
          sudo "${cfg.package}/bin/yabai" --load-sa

          echo "yabai scripting addition loaded..."

          # apps to ignore
          yabai -m rule --add app="^System (Preferences|Settings)$" manage=off
          yabai -m rule --add app="^Finder$" manage=off
          yabai -m rule --add app="^Activity Monitor$" manage=off
          yabai -m rule --add app="^Archive Utility$" manage=off
          yabai -m rule --add app="^Creative Cloud$" manage=off
          yabai -m rule --add app="^Login Options$" manage=off
          yabai -m rule --add app="^ClearVPN$" manage=off
          yabai -m rule --add app="^balenaEtcher$" manage=off
          yabai -m rule --add app="^Transmission$" manage=off
          yabai -m rule --add app="^PSI Bridge Secure Browser$" manage=off
          yabai -m rule --add app="^IntelliJ IDEA$" manage=off

          yabai -m signal --add event=window_created app="^Google Chrome$" action="yabai -m window --toggle float"
          yabai -m signal --add event=window_created app="^Brave Browser$" action="yabai -m window --toggle float"

          echo "yabai configuration loaded..."
        '';
      };

      environment.systemPath = [ "${cfg.package}/bin" ];
    }

    ############################################################
    # TCC stability
    #
    # macOS TCC (Accessibility) keys on the binary path. nix store paths
    # change every rebuild, silently revoking permission and causing yabai
    # to exit-loop under launchd. Pin the binary to /usr/local/bin/yabai
    # so TCC stays stable; only a real version bump re-triggers a re-grant.
    ############################################################
    (mkStableBinTCC {
      src = "${cfg.package}/bin/yabai";
      dst = stableBin;
      agent = "yabai";
      procName = "yabai";
      username = userCfg.username;
      permLabel = "Accessibility";
      programArgs = [ stableBin "-c" "${yabairc}" ];
      envVars = { PATH = "${stableBin}:/usr/local/bin:${config.environment.systemPath}"; };
    })
  ]);
}